(function(g){var window=this;var IBa=function(a){var b=a.Vb;this.buttonLabel=b.ypc_offer_button_text;this.g=a.ypcOfferButtonFormattedText;this.description=b.ypc_offer_description;this.heading=b.ypc_offer_headline;this.A=b.ypc_full_video_message;this.offerId=b.ypc_offer_id;this.B=b.ypc_buy_url;this.thumbnail=b.ypc_item_thumbnail;g.BL(this.thumbnail)||(this.thumbnail="");this.title=b.ypc_item_title;this.o=b.ypc_item_url;this.videoId=b.ypc_vid},Y$=function(){var a={H:"div",
ca:["ytp-drawer","html5-stop-propagation"],K:[{H:"div",M:"ytp-drawer-content",K:["{{content}}"]},{H:"button",ca:["ytp-drawer-close-button","ytp-button"],K:[g.vE()]},{H:"button",ca:["ytp-drawer-open-button","ytp-button"]}]};g.tX.call(this,a);this.P(this.sa["ytp-drawer-close-button"],"click",this.A);this.P(this.sa["ytp-drawer-open-button"],"click",this.show);this.o=new g.Ht(g.Ga(g.Up,this.element,"ytp-drawer-closed"),0);g.M(this,this.o);this.gc(null);this.hide()},Z$=function(a,b,c){g.qG.call(this);
this.A=0==c;this.g=new Y$;this.g.subscribe("close-clicked",this.KP,this);g.M(this,this.g);this.B=g.Cd("DIV");g.S(this.B,"html5-ypc-endscreen");this.o=new g.Y({H:"div",M:"html5-ypc-module",K:[{H:"div",M:"html5-ypc-action-heading",K:["{{heading}}"]},{H:"div",M:"html5-ypc-thumbnail",K:["{{thumbnail_element}}"]},{H:"div",M:"html5-ypc-title",K:["{{title}}"]},{H:"div",M:"html5-ypc-description",K:["{{description}}"]},{H:"button",ca:["html5-ypc-purchase","ytp-button"],K:["{{button_label}}"]}]});g.M(this,
this.o);this.C=this.o.sa["html5-ypc-purchase"];this.o.P(this.C,"click",this.wR,this);this.setData(b);this.Aa(a)},JBa=function(a){a.A||(a.B.appendChild(a.o.element),a.g.gc(null),g.cX(a.B,"block"))},$$=function(a){g.mX.call(this,a);
this.o=this.F=this.A=null;this.G=g.X(a);this.D=!1;this.I=new g.Ht(function(){var a=this.o;a.A||a.g.hide()},0,this);
this.B=null;this.C=new g.nG(this);g.M(this,this.C);this.load()};g.B(Y$,g.tX);Y$.prototype.A=function(){this.hide();this.V("close-clicked")};
Y$.prototype.hide=function(){this.o.stop();g.S(this.element,"ytp-drawer-closed")};
Y$.prototype.gc=function(a){a?(Y$.Z.gc.call(this,a),g.cX(this.element,"block")):g.cX(this.element,"none")};
Y$.prototype.show=function(){this.o.start()};g.p(Z$,g.qG);g.h=Z$.prototype;g.h.X=function(){g.qG.prototype.X.call(this);this.A||g.Jd(this.B)};
g.h.Aa=function(a){this.A||(this.g.Aa(a),this.g.gc(this.o.element),a.appendChild(this.B))};
g.h.setData=function(a){var b=a.title;a.o&&(b={H:"a",R:{href:a.o,target:"blank_"},K:[a.title]});var c="";a.thumbnail&&(c={H:"img",R:{src:a.thumbnail}});var d;a.g?d=g.WP(a.g):d=a.buttonLabel;this.o.update({heading:a.heading,title:b,thumbnail_element:c,description:a.description,button_label:d})};
g.h.KP=function(){this.V("ypcModuleCloseClicked")};
g.h.wR=function(){this.V("ypcContentRequest")};g.p($$,g.mX);g.h=$$.prototype;g.h.tT=function(a){this.o&&"dataupdated"==a||(this.unload(),this.load())};
g.h.load=function(){g.mX.prototype.load.call(this);this.C.P(this.g,"crn_ypc",this.GL,this);this.C.P(this.g,"crx_ypc",this.HL,this);this.C.P(this.g,"videodatachange",this.tT,this);var a=this.g.ga();this.A=new IBa(a);g.lO(this.G)||(this.B=new g.Y({H:"div",ca:["ytp-player-content","ytp-ypc-player-content"]}),g.SW(this.g,this.B.element,4));if(this.A.videoId&&!a.ypcPreview){for(var b={autoplay:"1",oauth_token:a.oauthToken,video_id:this.A.videoId,ypc_origin:a.videoId,ypc_preview:"1"},c=g.kta,d=0;d<c.length;d++){var e=
c[d];a.Vb.hasOwnProperty(e)&&(b[e]=a.Vb[e])}this.g.wo(b,!0)}else g.lO(this.G)||(this.A.videoId&&(this.F=new g.Y({H:"div",M:"html5-ypc-overlay",K:[this.A.A]}),this.F.Aa(this.B.element)),this.A.offerId&&(b=1E4,a.Vb.hasOwnProperty("ypc_overlay_timeout")&&(b=(0,window.parseInt)(a.Vb.ypc_overlay_timeout,10)),this.o=new Z$(this.B.element,this.A,b),this.o.subscribe("ypcContentRequest",this.zP,this),this.o.subscribe("ypcModuleCloseClicked",this.JQ,this),g.Opa(g.sW(this.g))&&(c=new g.TR(0x8000000000000,0x8000000000000,
{priority:g.RR.nk,namespace:"ypc"}),g.MW(this.g,[c])),c=this.o,c.A||c.g.show(),this.I.start(b))),!this.A.videoId&&this.o?(JBa(this.o),a=this.g,g.u1(a.app,void 0,a.playerType),this.D=!0,this.g.va("ypcStateChanged",!0)):a.ypcPreview?(this.g.va("ypcStateChanged",!0),g.QW(this.g,"ypc")):this.o||g.QW(this.g,"ypc")};
g.h.UT=function(){return this.D&&this.G.experiments.g("show_thumbnail_behind_ypc_offer_module")};
g.h.unload=function(){this.B&&(this.B.detach(),this.B.dispose(),this.B=null);g.pG(this.C);g.PW(this.g,"ypc");this.I.stop();g.bf(this.F,this.o);this.o=this.F=null;g.mX.prototype.unload.call(this);this.g.va("ypcStateChanged",!1)};
g.h.GL=function(){JBa(this.o);this.D=!0;this.g.va("ypcStateChanged",!0)};
g.h.HL=function(){var a=this.o;a.A||(g.cX(a.B,"none"),a.g.gc(a.o.element));this.D=!1;this.g.va("ypcStateChanged",!0)};
g.h.zP=function(){var a=this.A.B;a?g.WN(g.X(this.g))?g.iX(a):g.gX(a):this.A.offerId&&(this.g.isFullscreen()&&g.CW(this.g),this.g.va("onYpcContentRequest",this.A.offerId))};
g.h.JQ=function(){this.log({a:"ypc-checkout",label:"ypc-player-module-close-click",playertype:"html5"})};
g.h.log=function(a){g.GW(this.g,"ypc",a)};g.HZ.ypc=$$;})(_yt_player);
