(function(g){var window=this;var Qya=function(a,b,c,d){var e=b.jc();g.T(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.Mc(c,d?d:"mqdefault.jpg");var k=b instanceof g.ZP?g.uX(b.lengthSeconds):null,l=!!f;f=l&&"RD"==g.YR(f).type;var m=b instanceof g.ZP?b.xa:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,watch:g.U("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.Jn(c),is_live:m,is_list:l,is_mix:f,background:d?"background-image: url("+
d+")":""};b instanceof g.$R&&(c.playlist_length=b.getLength());a.update(c)},g7=function(a,b){g.tX.call(this,{H:"div",
ca:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.o=a;this.N=!1},h7=function(a){var b={H:"span",
M:"ytp-upnext-top",K:[{H:"span",M:"ytp-upnext-header",K:[g.U("YTP_PLAYLIST_UP_NEXT")]},{H:"span",M:"ytp-upnext-title",K:["{{title}}"]},{H:"span",M:"ytp-upnext-author",K:["{{author}}"]}]},c={href:"{{url}}","aria-label":g.U("YTP_AUTOPLAY_NEXT")};b={H:"div",M:"ytp-upnext",R:{"aria-label":"{{watch}}"},K:[{H:"div",M:"ytp-cued-thumbnail-overlay-image",R:{style:"{{background}}"}},b,{H:"a",M:"ytp-upnext-autoplay-icon",R:c,K:[{H:"svg",R:{height:"100%",version:"1.1",viewBox:"0 0 98 98",width:"100%"},K:[{H:"circle",
M:"ytp-svg-autoplay-circle",R:{cx:"49",cy:"49",fill:"#000","fill-opacity":"0.8",r:"48"}},{H:"circle",M:"ytp-svg-autoplay-ring",R:{cx:"-49",cy:"49","fill-opacity":"0",r:"46.5",stroke:"#FFFFFF","stroke-dasharray":"293","stroke-dashoffset":"-293","stroke-width":"4",transform:"rotate(-90)"}},{H:"polygon",M:"ytp-svg-autoplay-triangle",R:{fill:"#fff",points:"32,27 72,49 32,71"}}]}]},{H:"span",M:"ytp-upnext-bottom",K:[{H:"span",M:"ytp-upnext-cancel"},{H:"span",M:"ytp-upnext-paused",K:[g.U("YTP_AUTOPLAY_PAUSED_3")]}]},
{H:"span",M:"ytp-upnext-close"}]};g.Y.call(this,b);this.B=null;c=this.sa["ytp-upnext-cancel"];b=this.sa["ytp-upnext-close"];this.B=new g.Y({H:"button",ca:["ytp-upnext-cancel-button","ytp-button"],R:{tabindex:"0","aria-label":g.U("YTP_AUTOPLAY_CANCEL")},K:[g.U("YTP_CANCEL")]});g.M(this,this.B);this.B.W("click",this.cB,this);this.B.Aa(c);c=new g.Y({H:"button",ca:["ytp-upnext-close-button","ytp-button"],R:{"aria-label":g.U("YTP_AUTOPLAY_CANCEL")}});g.M(this,c);c.W("click",this.cB,this);c.Aa(b);this.o=
a;this.J=this.sa["ytp-svg-autoplay-ring"];this.F=this.D=this.A=this.C=null;this.G=new g.Ht(this.Xm,5E3,this);g.M(this,this.G);this.I=0;this.P(this.sa["ytp-upnext-autoplay-icon"],"click",this.iR);this.ZA();this.P(a,"autonavvisibility",this.ZA);this.P(a,"mdxnowautoplaying",this.xQ);this.P(a,"mdxautoplaycanceled",this.yQ);this.P(a,"mdxautoplayupnext",this.sD);3==this.o.Va()&&(a=(a=g.yW(g.tW(this.o)))?a.yI():null)&&this.sD(a)},Rya=function(a,b){a.C=b;
Qya(a,b,g.X(a.o),"hqdefault.jpg")},i7=function(a,b){a.A||(g.FG("a11y-announce",g.U("YTP_PLAYLIST_UP_NEXT")+" "+a.C.title),a.I=(0,g.SG)(),a.A=new g.Ht((0,g.z)(a.oq,a,b),25),a.oq(b));
g.Up(a.element,"ytp-upnext-autoplay-paused")},k7=function(a){j7(a);
a.I=(0,g.SG)();a.oq();g.S(a.element,"ytp-upnext-autoplay-paused")},j7=function(a){a.A&&(a.A.dispose(),a.A=null)},l7=function(a,b){b=void 0===b?!1:b;
var c=g.X(a.o);if(c.experiments.g("autonav_notifications")&&b&&window.Notification&&window.document.hasFocus){var d=window.Notification.permission;g.HW(a.o,"xwebnotifications",{permission:d});"default"==d?window.Notification.requestPermission():"granted"!=d||window.document.hasFocus()||(d=a.C.jc(),a.Xm(),a.D=new window.Notification(g.U("YTP_PLAYLIST_UP_NEXT"),{body:d.title,icon:d.Mc(c)}),a.F=a.P(a.D,"click",a.YQ),a.G.start())}j7(a);a.o.Fj(!1,b)},Sya=function(a){g7.call(this,a,"subscribecard-endscreen");
var b=a.ga();this.A=new g.Y({H:"div",M:"ytp-subscribe-card",K:[{H:"img",M:"ytp-author-image",R:{src:b.profilePicture}},{H:"div",M:"ytp-subscribe-card-right",K:[{H:"div",M:"ytp-author-name",K:[b.author]},{H:"div",M:"html5-subscribe-button-container"}]}]});g.M(this,this.A);this.A.Aa(this.element);this.B=new g.b1(g.U("YTP_SUBSCRIBE"),null,g.U("YTP_UNSUBSCRIBE"),null,!0,!1,b.Sl,b.subscribed,"trailer-endscreen",null,null,a);g.M(this,this.B);this.B.Aa(this.A.sa["html5-subscribe-button-container"]);this.hide()},
m7=function(a){var b=g.X(a);
b=b.A&&!b.D;g.Y.call(this,{H:"a",M:"ytp-videowall-still",R:{href:"{{url}}",target:b?"_blank":"","aria-label":"{{watch}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{H:"div",M:"ytp-videowall-still-image",R:{style:"{{background}}"}},{H:"span",M:"ytp-videowall-still-info",K:[{H:"span",M:"ytp-videowall-still-info-bg",K:[{H:"span",M:"ytp-videowall-still-info-content",R:g.pL||g.ef?{style:"will-change: opacity"}:void 0,K:[{H:"span",M:"ytp-videowall-still-info-title",
K:["{{title}}"]},{H:"span",M:"ytp-videowall-still-info-author",K:["{{author_and_views}}"]},{H:"span",M:"ytp-videowall-still-info-live",K:[g.U("YTP_LIVE")]},{H:"span",M:"ytp-videowall-still-info-duration",K:["{{duration}}"]}]}]}]},{H:"span",ca:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],K:[{H:"span",M:"ytp-videowall-still-listlabel-icon"},g.U("YTP_PLAYLIST"),{H:"span",M:"ytp-videowall-still-listlabel-length",K:[" (",{H:"span",K:["{{playlist_length}}"]},")"]}]},{H:"span",
ca:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],K:[{H:"span",M:"ytp-videowall-still-listlabel-mix-icon"},g.U("YTP_MIX"),{H:"span",M:"ytp-videowall-still-listlabel-length",K:[" (50+)"]}]}]});this.B=b;this.o=a;this.A=null;this.W("click",this.C);this.W("keypress",this.D);if(g.X(a).ba){a=a.app.da;b=this.element;g.H(a.g,b);g.pb(a.g,b);var c=String(a.G++);b.setAttribute("data-visual-id",c);g.$e(this,(0,g.z)(a.F,a,b))}},n7=function(a){g7.call(this,a,"videowall-endscreen");
this.ba=a;this.G=0;this.B=[];this.I=this.D=this.C=null;this.J=this.U=!1;this.F=new g.nG(this);g.M(this,this.F);this.L=new g.Ht(g.Ga(g.S,this.element,"ytp-show-tiles"),0);g.M(this,this.L);var b=new g.Y({H:"button",ca:["ytp-button","ytp-endscreen-previous"],R:{"aria-label":g.U("YTP_PREVIOUS")},K:[g.qE()]});g.M(this,b);b.Aa(this.element);b.W("click",this.ML,this);this.O=new g.$W({H:"div",M:"ytp-endscreen-content"});g.M(this,this.O);this.O.Aa(this.element);b=new g.Y({H:"button",ca:["ytp-button","ytp-endscreen-next"],
R:{"aria-label":g.U("YTP_NEXT")},K:[g.rE()]});g.M(this,b);b.Aa(this.element);b.W("click",this.LL,this);this.A=new h7(a);g.M(this,this.A);g.SW(this.o,this.A.element,4);this.hide()},o7=function(a){return g.TW(a.o)&&a.sq()&&!a.I},Tya=function(a){return(0,g.J)(a.Fg,function(a){return g.e_(a)})},p7=function(a){var b=a.Ks();
b!=a.U&&(a.U=b,a.o.V("autonavvisibility"))},q7=function(a){g.mX.call(this,a);
g.lE({});this.o=null;this.A=new g.nG(this);g.M(this,this.A);this.B=g.X(a);Uya(a)?this.o=new n7(this.g):this.B.pa?this.o=new Sya(this.g):this.o=new g7(this.g);g.M(this,this.o);g.SW(this.g,this.o.element,4);this.lC();this.A.P(a,"videodatachange",this.lC,this);this.A.P(a,"crn_endscreen",this.mL,this);this.A.P(a,"crx_endscreen",this.nL,this)},Uya=function(a){a=g.X(a);
return a.kd&&!a.pa};g.p(g7,g.tX);g7.prototype.create=function(){this.N=!0};
g7.prototype.destroy=function(){this.N=!1};
g7.prototype.sq=function(){return!1};
g7.prototype.Ks=function(){return!1};g.p(h7,g.Y);g.h=h7.prototype;g.h.Xm=function(){this.D&&(this.G.stop(),this.Ca(this.F),this.F=null,this.D.close(),this.D=null)};
g.h.ZA=function(){g.fX(this,g.uW(this.o))};
g.h.YQ=function(){window.focus();this.Xm()};
g.h.hide=function(){g.Y.prototype.hide.call(this)};
g.h.oq=function(a){a=a||g.X(this.o).experiments.o("autoplay_time")||1E4;var b=Math.min((0,g.SG)()-this.I,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-293*(a+1));1<=a&&3!=this.o.Va()?l7(this,!0):this.A&&this.A.start()};
g.h.iR=function(a){!g.Rd(this.B.element,g.dG(a))&&g.TZ(a,this.o)&&l7(this)};
g.h.cB=function(){g.IW(this.o,"autonavcancel");g.wW(this.o,!0)};
g.h.xQ=function(a){this.o.Va();this.show();i7(this,a)};
g.h.sD=function(a){this.o.Va();this.C&&this.C.jc().videoId==a.jc().videoId||Rya(this,a)};
g.h.yQ=function(){this.o.Va();j7(this);this.hide()};
g.h.X=function(){j7(this);this.Xm();g.Y.prototype.X.call(this)};g.p(Sya,g7);g.p(m7,g.Y);m7.prototype.Uj=function(){var a=this.A.jc().videoId,b=this.A.getPlaylistId();g.N1(this.o.app,a,this.A.Xd,b,void 0,void 0,void 0)};
m7.prototype.C=function(a){g.WW(this.o,this.element);g.TZ(a,this.o,this.B,this.A.Xd||void 0)&&this.Uj()};
m7.prototype.D=function(a){switch(a.keyCode){case 13:case 32:g.iG(a)||(this.Uj(),g.kG(a))}};g.p(n7,g7);g.h=n7.prototype;g.h.create=function(){g7.prototype.create.call(this);var a=this.o.ga();a&&(this.C=Tya(a),this.D=a);this.xh();this.F.P(this.o,"appresize",this.xh);this.F.P(this.o,"videodatachange",this.NL);this.F.P(this.o,"autonavchange",this.Iz);this.F.P(this.o,"autonavcancel",this.KL);this.F.P(this.element,"transitionend",this.pS)};
g.h.destroy=function(){g.pG(this.F);g.bf(this.B);this.B=[];this.C=null;g7.prototype.destroy.call(this);g.Up(this.element,"ytp-show-tiles");this.L.stop()};
g.h.sq=function(){return 1!=this.D.autonavState};
g.h.show=function(){g7.prototype.show.call(this);g.Up(this.element,"ytp-show-tiles");g.X(this.o).isMobile?g.It(this.L):this.L.start();(this.J||this.I&&this.I!=this.D.clientPlaybackNonce)&&g.wW(this.o,!1);var a=o7(this);g.TW(this.o)&&g.X(this.o).experiments.g("ui_logging")&&g.HW(this.o,"end",{cancelButtonShow:a?"1":"0",state:this.sq()?"enabled":"disabled"});a?(p7(this),2==this.D.autonavState?g.X(this.o).experiments.g("fast_autonav_in_background")&&3==this.o.Bh()?l7(this.A,!0):i7(this.A):3==this.D.autonavState&&
k7(this.A)):(g.wW(this.o,!0),p7(this))};
g.h.hide=function(){g7.prototype.hide.call(this);k7(this.A);p7(this)};
g.h.pS=function(a){g.dG(a)==this.element&&this.xh()};
g.h.xh=function(){if(this.C&&this.C.length){g.S(this.element,"ytp-endscreen-paginate");var a=g.Hh(this.element),b=a.width/a.height,c=96/54,d=2,e=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.C.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(d<f||e<k);){var q=d/2,r=e/2,w=d<=f-2&&n>=r*m,A=e<=k-2&&n>=q*m;if((q+1)/r*c/b>b/(q/(r+1)*c)&&A)n-=q*m,e+=2;else if(w)n-=r*m,d+=2;else if(A)n-=q*m,e+=2;else break}c=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=d)&&(c=!0);m=96*
d;n=54*e;b=m/n<b?a.height/n:a.width/m;b=Math.min(b,2);m*=b;n*=b;m*=g.$c(a.width/m||1,1,1.21);n*=g.$c(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.O.element;g.Gh(a,m,n);g.oh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});Rya(this.A,this.C[0]);g.T(this.element,"ytp-endscreen-takeover",o7(this));p7(this);m+=4;n+=4;for(f=b=0;f<d;f++)for(k=0;k<e;k++)if(q=b,r=0,c&&f>=d-2&&k>=e-2?r=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(r=2):r=2),q=g.ad(q+this.G,l),0!=
r){w=this.B[b];w||(w=new m7(this.o),this.B[b]=w,a.appendChild(w.element));A=Math.floor(n*k/e);var D=Math.floor(m*f/d),I=Math.floor(n*(k+r)/e)-A-4,N=Math.floor(m*(f+r)/d)-D-4;g.vh(w.element,D,A);g.Gh(w.element,N,I);g.oh(w.element,"transitionDelay",(k+f)/20+"s");g.T(w.element,"ytp-videowall-still-mini",1==r);g.T(w.element,"ytp-videowall-still-large",2<r);r=w;q=this.C[q];r.A=q;Qya(r,q,g.X(r.o),g.Sp(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg");w=q.Xd;q=r.o;g.X(q).ba&&(q=q.app.da,
r=r.element,w=w&&w.itct,A=r.getAttribute("data-visual-id"),g.H(q.g,r),g.UW(q,"onLogServerVeCreated",{id:A,tracking_params:w}));b++}g.T(this.element,"ytp-endscreen-paginate",b<l);for(d=this.B.length-1;d>=b;d--)e=this.B[d],g.Jd(e.element),g.af(e);this.B.length=b}};
g.h.NL=function(){var a=this.o.ga();this.D!=a&&(this.G=0,this.C=Tya(a),this.D=a,this.xh())};
g.h.LL=function(){this.G+=this.B.length;this.xh()};
g.h.ML=function(){this.G-=this.B.length;this.xh()};
g.h.FK=function(){return!!this.A.A};
g.h.Iz=function(a){1==a?(this.J=!1,this.I=this.D.clientPlaybackNonce,j7(this.A),this.g&&this.xh()):(this.J=!0,this.g&&o7(this)&&(2==a?i7(this.A):3==a&&k7(this.A)))};
g.h.KL=function(a){if(a){for(a=0;a<this.B.length;a++)g.XW(this.ba,this.B[a].element,!0);this.Iz(1)}else this.I=null,this.J=!1;this.xh()};
g.h.Ks=function(){return this.g&&o7(this)};g.p(q7,g.mX);g.h=q7.prototype;g.h.Ez=function(){var a=this.g.ga(),b=!Uya(this.g)||!(!a.Fg||!a.Fg.length);a=g.sQ(a,"ypc_module");var c=g.O1(this.g.app);return(b||!1)&&!a&&!c};
g.h.Dz=function(){return this.o.Ks()};
g.h.CK=function(){return this.Dz()?this.o.FK():!1};
g.h.X=function(){g.QW(this.g,"endscreen");g.mX.prototype.X.call(this)};
g.h.load=function(){g.mX.prototype.load.call(this);this.o.show();g.X(this.g).pa&&.01>Math.random()&&g.HW(this.g,"end",{trailerEndscreenShow:1})};
g.h.unload=function(){g.mX.prototype.unload.call(this);this.o.hide();this.o.destroy()};
g.h.mL=function(a){this.Ez()&&(this.o.N||this.o.create(),"load"==a.getId()&&this.load())};
g.h.nL=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.lC=function(){g.QW(this.g,"endscreen");var a=Math.max(1E3*(this.g.ga().lengthSeconds-10),0);a=new g.UR(a,0x8000000000000,{id:"preload",namespace:"endscreen"});var b=new g.UR(0x8000000000000,0x8000000000000,{id:"load",priority:g.SR.qF,namespace:"endscreen"});g.NW(this.g,[a,b])};g.HZ.endscreen=q7;})(_yt_player);
